var annotated =
[
    [ "FW", "namespace_f_w.html", "namespace_f_w" ],
    [ "AllocHeader", "struct_alloc_header.html", "struct_alloc_header" ],
    [ "AppEnvironment", "class_app_environment.html", "class_app_environment" ],
    [ "Coin", "struct_coin.html", "struct_coin" ],
    [ "Environment", "class_environment.html", "class_environment" ],
    [ "HuffmanTree", "struct_huffman_tree.html", "struct_huffman_tree" ],
    [ "KernelConfig", "struct_kernel_config.html", "struct_kernel_config" ],
    [ "LodePNG_CompressSettings", "struct_lode_p_n_g___compress_settings.html", "struct_lode_p_n_g___compress_settings" ],
    [ "LodePNG_Decoder", "struct_lode_p_n_g___decoder.html", "struct_lode_p_n_g___decoder" ],
    [ "LodePNG_DecodeSettings", "struct_lode_p_n_g___decode_settings.html", "struct_lode_p_n_g___decode_settings" ],
    [ "LodePNG_DecompressSettings", "struct_lode_p_n_g___decompress_settings.html", "struct_lode_p_n_g___decompress_settings" ],
    [ "LodePNG_Encoder", "struct_lode_p_n_g___encoder.html", "struct_lode_p_n_g___encoder" ],
    [ "LodePNG_EncodeSettings", "struct_lode_p_n_g___encode_settings.html", "struct_lode_p_n_g___encode_settings" ],
    [ "LodePNG_InfoColor", "struct_lode_p_n_g___info_color.html", "struct_lode_p_n_g___info_color" ],
    [ "LodePNG_InfoPng", "struct_lode_p_n_g___info_png.html", "struct_lode_p_n_g___info_png" ],
    [ "LodePNG_InfoRaw", "struct_lode_p_n_g___info_raw.html", "struct_lode_p_n_g___info_raw" ],
    [ "LodePNG_IText", "struct_lode_p_n_g___i_text.html", "struct_lode_p_n_g___i_text" ],
    [ "LodePNG_Text", "struct_lode_p_n_g___text.html", "struct_lode_p_n_g___text" ],
    [ "LodePNG_Time", "struct_lode_p_n_g___time.html", "struct_lode_p_n_g___time" ],
    [ "LodePNG_UnknownChunks", "struct_lode_p_n_g___unknown_chunks.html", "struct_lode_p_n_g___unknown_chunks" ],
    [ "Option", "class_option.html", "class_option" ],
    [ "OtraceInput", "struct_otrace_input.html", "struct_otrace_input" ],
    [ "ProfileTimer", "struct_profile_timer.html", "struct_profile_timer" ],
    [ "RanrotA", "class_ranrot_a.html", "class_ranrot_a" ],
    [ "RayStruct", "struct_ray_struct.html", "struct_ray_struct" ],
    [ "SafeSpinlock", "class_safe_spinlock.html", "class_safe_spinlock" ],
    [ "ucvector", "structucvector.html", "structucvector" ],
    [ "uivector", "structuivector.html", "structuivector" ],
    [ "vector", "structvector.html", "structvector" ]
];